using System.ComponentModel.DataAnnotations;
using CustomAttributeForPopOver.Components;
using CustomAttributeForPopOver.Resources;

namespace CustomAttributeForPopOver.Models
{
    /// <summary>
    /// Model view class where the attributes - Display and DataContentAnnotation is presented on the properties itself
    /// And where the metadata type is not involved
    /// </summary>
    public class MainPageModelView
    {
        [Display(ResourceType = typeof(Labels), Name = "Title")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Title), Content = nameof(Labels.Title_PopOverDescription))]
        public string Title { get; set; }

        [Display(ResourceType = typeof(Labels), Name = "Description")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Description), Content = nameof(Labels.Description_PopOverDescription))]
        public string Description { get; set; }
        
        [Display(ResourceType = typeof(Labels), Name = "Author")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Author), Content = nameof(Labels.Author_PopOverDescription))]
        public string Author { get; set; }
    }
    
    /// <summary>
    /// Model view class where the attributes - Display and DataContentAnnotation is NOT presented on the properties itself
    /// since there are some files which are generated by ORMs such as EF or other, so metadata type is being used
    /// </summary>
    public class MainPageWithMetadataTypeModelViewMetadataType
    {
        [Display(ResourceType = typeof(Labels), Name = "Title")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Title), Content = nameof(Labels.Title_PopOverDescription))]
        public string Title { get; set; }

        [Display(ResourceType = typeof(Labels), Name = "Description")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Description), Content = nameof(Labels.Description_PopOverDescription))]
        public string Description { get; set; }
        
        [Display(ResourceType = typeof(Labels), Name = "Author")]
        [DataContentAnnotation(ResourceType = typeof(Labels), Title = nameof(Labels.Author), Content = nameof(Labels.Author_PopOverDescription))]
        public string Author { get; set; }
    }
    [MetadataType(typeof(MainPageWithMetadataTypeModelViewMetadataType))]
    public class MainPageWithMetadataTypeModelView
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
    }
}